import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by MusDev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        <SessionProvider>

        <Toaster position="top-right"/>
        <main className="flex items-center justify-center min-h-screen ">
        {children}
        </main>
        </SessionProvider>
      </body>
    </html>
  );
}
